[ req ]
default_bits        = 4096          # Mayor seguridad para la raíz
default_md          = sha384        # Algoritmo de hash más robusto sha256, sha384 o sha512
distinguished_name = ca_dn
x509_extensions    = v3_ca
prompt             = no

[ ca_dn ]
C  = SG
ST = Singapore
L  = Singapore
O  = WowSource Inc
OU = www.wowsource.net
CN = WowSource Root CA

[ v3_ca ]
# Configuración fundamental para una CA
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints       = critical, CA:TRUE
keyUsage               = critical, keyCertSign, cRLSign