[req]
default_bits       = 2048
default_md         = sha384 	# Algoritmo de hash más robusto sha256, sha384 o sha512
distinguished_name = req_distinguished_name
req_extensions     = v3_req
prompt            = no

[req_distinguished_name]
C  = SG
ST = Singapore
L  = Singapore
O  = WowSource Inc
OU = wowsource Web
CN = wowsource.net

[v3_req]
basicConstraints = CA:FALSE
keyUsage = digitalSignature, keyEncipherment, nonRepudiation
extendedKeyUsage = serverAuth, clientAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = wowsource.net
DNS.2 = idev.net
DNS.3 = localhost
IP.1  = 192.168.0.3